name: Test Discord Webhook

on:
  workflow_dispatch:

jobs:
  test-discord-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Post test announcement to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VERSION: "2.4.2"
        run: |
          RELEASE_NOTES=$(awk '/^## Version \[${{ env.VERSION }}\]/ {flag=1; next} /^## Version \[/ {flag=0} flag' CHANGELOG.md)
          ANNOUNCEMENT_BODY="🚀 **New Release: ${{ env.VERSION }}**\n\n${RELEASE_NOTES}\n\n[Download the release](https://github.com/${{ github.repository }}/releases/tag/${{ env.VERSION }})"
          ESCAPED_BODY=$(echo "$ANNOUNCEMENT_BODY" | jq -Rs 'gsub("\\n"; "\n")')
          curl -H "Content-Type: application/json" \
               -d "{\"content\": ${ESCAPED_BODY}}" \
               $DISCORD_WEBHOOK_URL
